version: 2
jobs:
  test:
    machine: true
    steps:
    - checkout
    - run:
        name: create docker network
        command: docker network create app_network
    - run:
        name: dockerize install
        command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
        environment:
          DOCKERIZE_VERSION: v0.3.0
    - run:
        name: docker-compose up
        command: docker-compose up -d
    - run:
        command: dockerize -wait tcp://127.0.0.1:13306 -timeout 120s
    - run:
        name: ping-test
        command: docker-compose exec user ping db-user:3306 -c 5
    - run:
        name: check ps
        command: docker ps
    - run:
        name: migration
        command: docker-compose exec user go run migration/migration.go
    - run:
        name: testing
        command: docker-compose exec user make
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - test

# Original config.yml file:
# version: 2.1
# 
# jobs:
#   test:
#     machine: true
#     steps:
# 
#       - checkout
# 
#       - run:
#           name: create docker network
#           command: docker network create app_network
#       
#       - run:
#           name: dockerize install
#           command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
#           environment:
#             DOCKERIZE_VERSION: v0.3.0
# 
#       - run:
#           name: docker-compose up
#           command: docker-compose up -d
# 
#       - run: dockerize -wait tcp://127.0.0.1:13306 -timeout 120s
# 
#       - run:
#           name: ping-test
#           command: docker-compose exec user ping db-user:3306 -c 5
# 
#       - run:
#           name: check ps
#           command: docker ps
#       
#       - run:
#           name: migration
#           command: docker-compose exec user go run migration/migration.go
#       
#       - run:
#           name: testing
#           command: docker-compose exec user make
# 
# workflows:
#   version: 2.1
#   build-test-and-deploy:
#     jobs:
#       - test