apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: ap
    back: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap
      back: user
  template:
    metadata:
      labels:
        app: ap
        back: user
    spec:
      containers:
      - name: user
        image: snd1231/user
        ports:
        - containerPort: 9001
        command:
          - sh
          - -c
          - go run main.go
        env:
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "a1b2V4d5"
          - name: DB_NAME
            value: "ramen_app"
          - name: DB_ADDRESS
            value: "user-db.cdvmgnpfzvjx.ap-northeast-1.rds.amazonaws.com:3306"
