version: 2

jobs:
  test:
    machine: true
    steps:

      - checkout

      - run:
          name: create docker network
          command: docker network create app_network

      - run:
          name: check
          command: ls;cd project;ls

      - run:
          name: docker-compose up
          command: docker-compose up -d
      
      - run:
          name: wait connect DB
          command: docker exec user-service-container dockerize -timeout 180s -wait tcp://db-user:3306

      - run:
          name: testing
          command: docker exec user-service-container make

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
