version: 2

jobs:
  test:
    machine: true
    steps:

      - checkout

      - run:
          name: create docker network
          command: docker network create app_network
      
      - run:
          name: dockerize install
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

       - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      
      - run:
          name: ping-test
          command: docker-compose exec user-service-container ping user-db -c 5

      - run:
          name: testing
          command: docker exec user-service-container make

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
